name: Damonx Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello from DAMON XU"

      - name: Print goodbye
        run: echo "Bye!! damonx! hahahah"
